name: Skript-Packet
author: Anarchick
description: A skript addon for packets
version: 1.1
main: fr.anarchick.skriptpacket.SkriptPacket
depend: [Skript, ProtocolLib]
softdepend: [skript-reflect]
website: www.github.com/Anarchick/skript-packet